baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "答案导航"
theme = "hugo-webstack"

disablePathToLower = true
copyright = "Darwin"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  minifyOutput = true

[params]
  keywords = "答案导航,优质资源,网站导航,工具集合,webstack,hugo"
  description = "答案导航 - 专注优质资源网站导航，收录精品工具、学习资源、实用网站。"
  subtitle = "专注优质资源网站导航"

[params.search]
  enable = true

[params.darkmode]
  enable = true

[params.edit]
  enable = false
  url = "https://github.com/oulh/nav/blob/main/data/webstack.yml"

[params.github]
  enable = false
  url = "https://github.com/oulh/nav"

[permalinks]
  404 = "/404.html"

[params.pinyin]
  enable = true